# Generated by Django 4.0.2 on 2022-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='name',
            new_name='fullname',
        ),
    ]
