# Generated by Django 4.0.2 on 2022-03-12 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_name_inquiry_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inq_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
