# Generated by Django 4.0.2 on 2022-03-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_role'),
        ('client', '0004_inquiry_inq_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book_time', models.DateTimeField(auto_now_add=True)),
                ('pay_type', models.CharField(choices=[('Online', 'Online'), ('On Clinic', 'On Clinic')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientuser')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
            ],
        ),
    ]
