# Generated by Django 4.0.2 on 2022-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_bookingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtest',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=50),
        ),
    ]
