# Generated by Django 4.0.2 on 2022-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_bookingtest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtest',
            name='pay_verify',
            field=models.BooleanField(default=False),
        ),
    ]
