# Generated by Django 4.0.2 on 2022-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_test_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='approve_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
