# Generated by Django 4.0.2 on 2022-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_test_approve_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
