# Generated by Django 4.0.2 on 2022-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_test_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_on',
            field=models.BooleanField(default=False),
        ),
    ]
