# Generated by Django 4.0.2 on 2022-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_test_test_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Doctor', max_length=50),
        ),
    ]
